name: Reid Simpson
favicon: null
layout_spectrum: 0.05165690975263715
typography_spectrum: 0.27255212026648223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8605020153336227
  lightness: 0.6896931990049779
  saturation: 0.20332148158922791
  rhythmicContrast: 0.8348859190009534
purpose: []
