name: Reid J. Simpson
favicon: null
layout_spectrum: 0.74123
typography_spectrum: 0.543
title: Reid J. Simpson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8ac8f7'
    - '#ffffff'
    - '#0d0d0f'
    - '#747579'
    - '#2c3135'
  brandStrength: 0.8605020153336227
  lightness: 0.6896931990049779
  saturation: 0.20332148158922791
  rhythmicContrast: 0.8348859190009534
purpose: []
